// Code generated by protoc-gen-go. DO NOT EDIT.
// source: uri.v1.proto

package rambo_v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RocosUriScheme int32

const (
	RocosUriScheme_GRPC RocosUriScheme = 0
)

var RocosUriScheme_name = map[int32]string{
	0: "GRPC",
}

var RocosUriScheme_value = map[string]int32{
	"GRPC": 0,
}

func (x RocosUriScheme) String() string {
	return proto.EnumName(RocosUriScheme_name, int32(x))
}

func (RocosUriScheme) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_aec01c4c5b7407f6, []int{0}
}

type RocosUri struct {
	Scheme               RocosUriScheme    `protobuf:"varint,1,opt,name=scheme,proto3,enum=rambo_v1.RocosUriScheme" json:"scheme,omitempty"`
	Authority            string            `protobuf:"bytes,2,opt,name=authority,proto3" json:"authority,omitempty"`
	Path                 *RocosUriPath     `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Query                map[string]string `protobuf:"bytes,4,rep,name=query,proto3" json:"query,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *RocosUri) Reset()         { *m = RocosUri{} }
func (m *RocosUri) String() string { return proto.CompactTextString(m) }
func (*RocosUri) ProtoMessage()    {}
func (*RocosUri) Descriptor() ([]byte, []int) {
	return fileDescriptor_aec01c4c5b7407f6, []int{0}
}

func (m *RocosUri) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RocosUri.Unmarshal(m, b)
}
func (m *RocosUri) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RocosUri.Marshal(b, m, deterministic)
}
func (m *RocosUri) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RocosUri.Merge(m, src)
}
func (m *RocosUri) XXX_Size() int {
	return xxx_messageInfo_RocosUri.Size(m)
}
func (m *RocosUri) XXX_DiscardUnknown() {
	xxx_messageInfo_RocosUri.DiscardUnknown(m)
}

var xxx_messageInfo_RocosUri proto.InternalMessageInfo

func (m *RocosUri) GetScheme() RocosUriScheme {
	if m != nil {
		return m.Scheme
	}
	return RocosUriScheme_GRPC
}

func (m *RocosUri) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *RocosUri) GetPath() *RocosUriPath {
	if m != nil {
		return m.Path
	}
	return nil
}

func (m *RocosUri) GetQuery() map[string]string {
	if m != nil {
		return m.Query
	}
	return nil
}

type RocosUriPath struct {
	Project              string   `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	Callsign             string   `protobuf:"bytes,2,opt,name=callsign,proto3" json:"callsign,omitempty"`
	Subsystem            string   `protobuf:"bytes,3,opt,name=subsystem,proto3" json:"subsystem,omitempty"`
	Component            string   `protobuf:"bytes,4,opt,name=component,proto3" json:"component,omitempty"`
	Topic                string   `protobuf:"bytes,5,opt,name=topic,proto3" json:"topic,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RocosUriPath) Reset()         { *m = RocosUriPath{} }
func (m *RocosUriPath) String() string { return proto.CompactTextString(m) }
func (*RocosUriPath) ProtoMessage()    {}
func (*RocosUriPath) Descriptor() ([]byte, []int) {
	return fileDescriptor_aec01c4c5b7407f6, []int{1}
}

func (m *RocosUriPath) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RocosUriPath.Unmarshal(m, b)
}
func (m *RocosUriPath) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RocosUriPath.Marshal(b, m, deterministic)
}
func (m *RocosUriPath) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RocosUriPath.Merge(m, src)
}
func (m *RocosUriPath) XXX_Size() int {
	return xxx_messageInfo_RocosUriPath.Size(m)
}
func (m *RocosUriPath) XXX_DiscardUnknown() {
	xxx_messageInfo_RocosUriPath.DiscardUnknown(m)
}

var xxx_messageInfo_RocosUriPath proto.InternalMessageInfo

func (m *RocosUriPath) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

func (m *RocosUriPath) GetCallsign() string {
	if m != nil {
		return m.Callsign
	}
	return ""
}

func (m *RocosUriPath) GetSubsystem() string {
	if m != nil {
		return m.Subsystem
	}
	return ""
}

func (m *RocosUriPath) GetComponent() string {
	if m != nil {
		return m.Component
	}
	return ""
}

func (m *RocosUriPath) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func init() {
	proto.RegisterEnum("rambo_v1.RocosUriScheme", RocosUriScheme_name, RocosUriScheme_value)
	proto.RegisterType((*RocosUri)(nil), "rambo_v1.RocosUri")
	proto.RegisterMapType((map[string]string)(nil), "rambo_v1.RocosUri.QueryEntry")
	proto.RegisterType((*RocosUriPath)(nil), "rambo_v1.RocosUriPath")
}

func init() { proto.RegisterFile("uri.v1.proto", fileDescriptor_aec01c4c5b7407f6) }

var fileDescriptor_aec01c4c5b7407f6 = []byte{
	// 297 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0x41, 0x4b, 0xc3, 0x30,
	0x1c, 0xc5, 0xcd, 0xd6, 0xcd, 0xf6, 0xbf, 0x31, 0x46, 0x10, 0x09, 0x43, 0xa1, 0xec, 0x54, 0x76,
	0x28, 0x6e, 0xbb, 0x0c, 0xaf, 0x22, 0x5e, 0x67, 0xc4, 0xb3, 0xa4, 0x21, 0xd8, 0x6a, 0xdb, 0xd4,
	0x24, 0x2d, 0xf4, 0x8b, 0xf8, 0x4d, 0xbd, 0x4b, 0xd3, 0x76, 0x55, 0x76, 0xeb, 0x7b, 0xef, 0xc7,
	0xe3, 0xfd, 0x1b, 0x98, 0x97, 0x2a, 0x09, 0xab, 0x6d, 0x58, 0x28, 0x69, 0x24, 0x76, 0x15, 0xcb,
	0x22, 0xf9, 0x56, 0x6d, 0xd7, 0x3f, 0x08, 0x5c, 0x2a, 0xb9, 0xd4, 0xaf, 0x2a, 0xc1, 0x77, 0x30,
	0xd5, 0x3c, 0x16, 0x99, 0x20, 0xc8, 0x47, 0xc1, 0x62, 0x47, 0xc2, 0x9e, 0x0b, 0x7b, 0xe6, 0xc5,
	0xe6, 0xb4, 0xe3, 0xf0, 0x0d, 0x78, 0xac, 0x34, 0xb1, 0x54, 0x89, 0xa9, 0xc9, 0xc8, 0x47, 0x81,
	0x47, 0x07, 0x03, 0x6f, 0xc0, 0x29, 0x98, 0x89, 0xc9, 0xd8, 0x47, 0xc1, 0x6c, 0x77, 0x7d, 0xde,
	0x76, 0x64, 0x26, 0xa6, 0x96, 0xc1, 0x7b, 0x98, 0x7c, 0x95, 0x42, 0xd5, 0xc4, 0xf1, 0xc7, 0xc1,
	0x6c, 0x77, 0x7b, 0x0e, 0x87, 0xcf, 0x4d, 0xfe, 0x98, 0x1b, 0x55, 0xd3, 0x96, 0x5d, 0x1d, 0x00,
	0x06, 0x13, 0x2f, 0x61, 0xfc, 0x29, 0x6a, 0xbb, 0xdd, 0xa3, 0xcd, 0x27, 0xbe, 0x82, 0x49, 0xc5,
	0xd2, 0x52, 0x74, 0xd3, 0x5a, 0x71, 0x3f, 0x3a, 0xa0, 0xf5, 0x37, 0x82, 0xf9, 0xdf, 0x15, 0x98,
	0xc0, 0x65, 0xa1, 0xe4, 0x87, 0xe0, 0xa6, 0x2b, 0xe8, 0x25, 0x5e, 0x81, 0xcb, 0x59, 0x9a, 0xea,
	0xe4, 0x3d, 0xef, 0x7a, 0x4e, 0xba, 0xb9, 0x5f, 0x97, 0x91, 0xae, 0xb5, 0x11, 0x99, 0x3d, 0xd3,
	0xa3, 0x83, 0xd1, 0xa4, 0x5c, 0x66, 0x85, 0xcc, 0x45, 0x6e, 0x88, 0xd3, 0xa6, 0x27, 0xa3, 0x19,
	0x67, 0x64, 0x91, 0x70, 0x32, 0x69, 0xc7, 0x59, 0xb1, 0x59, 0xc1, 0xe2, 0xff, 0xbf, 0xc6, 0x2e,
	0x38, 0x4f, 0xf4, 0xf8, 0xb0, 0xbc, 0x88, 0xa6, 0xf6, 0xf5, 0xf6, 0xbf, 0x01, 0x00, 0x00, 0xff,
	0xff, 0x5f, 0xd7, 0x3f, 0xea, 0xcd, 0x01, 0x00, 0x00,
}
